### ISSUE TITLE
complier environment

### ISSUE THREAD

**Issue by Ghaker** [joriswit/YASS#1]
I'm compile fpc 3.3.1 failed. Could you give me fpc-3.3.1.i386-win32.cross.android.exe
I used fpc 3.0.4

**Comment by Ghaker** [comment]
I need x64.so to build yass.apk

**Comment by joriswit** [comment]
To build a development 3.3.1 version, I followed the instructions here to build it from source: https://wiki.freepascal.org/Android

However, since FPC 3.2 is released now, I recommend using that instead. You can download it here:
https://sourceforge.net/projects/freepascal/files/Win32/3.2.0/

As for x64; YASS can currently only be compiled as a 32 bits app.
